import Foundation
func check(_ condition: Bool, _ message: String) { precondition(condition, message) }
var motion = LidMotion()
motion.update(angle: 70)
check(!motion.isFoldActive, "Low-angle startup must remain clear")
motion.update(angle: 69)
check(motion.isFoldActive && motion.isClosing, "Closing arms folding")
for _ in 0..<1800 { motion.update(angle: 69) }
check(motion.isFoldActive, "Stationary closing holds")
motion.update(angle: 80)
check(motion.isFoldActive && !motion.isClosing, "Opening keeps the reverse animation active")
for _ in 0..<1800 { motion.update(angle: 80) }
check(motion.isFoldActive, "Stationary opening holds")
motion.update(angle: 79)
check(motion.isFoldActive && motion.isClosing, "Direction reversal remains continuous")
motion.update(angle: 115)
check(!motion.isFoldActive, "Fully open clears overlay")
motion.reset()
motion.update(angle: 50)
check(!motion.isFoldActive, "Escape/reset does not re-arm a stationary lid")
motion.beginOpening()
motion.update(angle: 20)
check(motion.isFoldActive && !motion.isClosing, "Wake starts an opening session")
motion.update(angle: 60)
check(motion.isFoldActive && !motion.isClosing, "Wake opening continues")
motion.update(angle: 115)
check(!motion.isFoldActive, "Wake animation ends at open angle")
motion.beginOpening()
motion.update(angle: 130)
check(!motion.isFoldActive, "Wake with fully open lid remains clear")
motion.beginOpening()
motion.update(angle: 999)
check(!motion.isFoldActive, "Invalid sensor sample clears")
motion.update(angle: 100, startAngle: 90)
check(!motion.isFoldActive, "Custom open threshold works")
print("PASS: startup, closing, both stationary holds, opening, reversal, full opening, reset, wake, invalid samples, custom threshold")
